Repository bridge-core/editor, pull requests merged in 2022-12, with the labels that each got.

#753 feat: solid views
  package-lock.json
  package.json
  src/components/Solid/Directives/Ripple.css
  src/components/Solid/Directives/Ripple.ts
  src/components/Solid/DirectoryViewer/Common/Name.css
  src/components/Solid/DirectoryViewer/Common/Name.tsx
  src/components/Solid/DirectoryViewer/DirectoryView.tsx
  src/components/Solid/Icon/IconText.tsx
  src/components/Solid/Icon/SolidIcon.tsx
  src/components/Solid/Inputs/Button/SolidButton.tsx
  src/components/Solid/toSignal.ts
  src/components/Solid/toVue.ts
  src/components/TabSystem/TabSystem.vue
  src/components/TabSystem/WelcomeScreen.vue
  src/components/UIElements/DirectoryViewer/Common/BaseWrapper.ts
  src/components/UIElements/DirectoryViewer/DirectoryView/DirectoryView.vue
  src/components/UIElements/DirectoryViewer/DirectoryView/DirectoryWrapper.ts
  src/components/UIElements/DirectoryViewer/FileView/FileWrapper.ts
  tsconfig.json
  vite.config.ts
Labels: feature

#752 fix: duplicated entries within virtual fs
  src/components/FileSystem/Virtual/Stores/IndexedDb.ts
Labels: bug

#751 fix: rename files on mobile
  src/components/UIElements/DirectoryViewer/Common/Name.vue
Labels: bug

#750 fix(IndexedDb): format compat
  src/components/FileSystem/Virtual/Stores/IndexedDb.ts
Labels: bug

#749 upd: use last modified timestamp
  src-tauri/src/main.rs
  src/components/FileSystem/Virtual/FileHandle.ts
  src/components/FileSystem/Virtual/Stores/BaseStore.ts
  src/components/FileSystem/Virtual/Stores/IndexedDb.ts
  src/components/FileSystem/Virtual/Stores/TauriFs.ts
Labels: feature

#756 feat(tauri): import projects
  src/components/FileSystem/FileSystem.ts
  src/components/PackExplorer/HomeView/HomeView.vue
  src/components/PackExplorer/HomeView/ImportOldProjects.vue
  src/components/PackExplorer/HomeView/SetupView.vue
  src/locales/en.json
Labels: feature

#754 feat: open with snowstorm
  src/components/UIElements/DirectoryViewer/ContextMenu/Actions/OpenWith/Snowstorm.ts
Labels: feature

#761 feat: fast directory copying
  src-tauri/src/fs_extra.rs
  src-tauri/src/main.rs
  src/components/FileSystem/FileSystem.ts
Labels: feature

#763 fix: inactive tab display
  src/components/TabSystem/TabBar.vue
  src/components/TabSystem/TabSystem.ts
Labels: bug

#760 feat: fast path for getDirectoryHandle
  src/components/Data/DataLoader.ts
  src/components/FileSystem/Fast/getDirectoryHandle.ts
  src/components/FileSystem/FileSystem.ts
  src/components/FileSystem/Virtual/DirectoryHandle.ts
  src/components/FileSystem/Virtual/FileHandle.ts
  src/components/FileSystem/Virtual/Handle.ts
  src/components/FileSystem/Virtual/getParent.ts
  src/components/FileSystem/Virtual/pathFromHandle.ts
Labels: feature

#768 fix: openInSplitScreen
  src/components/Editors/ThreePreview/ThreePreviewTab.ts
  src/components/Projects/Project/Project.ts
  src/components/TabSystem/TabBar.vue
Labels: bug

#767 feat: import multiple projects
  src/components/Compiler/Window/OutputFolders.vue
  src/components/FileSystem/Pickers/showFolderPicker.ts
  src/components/ImportFolder/ImportProjects.ts
  src/components/PackExplorer/HomeView/ImportOldProjects.vue
  src/components/Projects/ProjectManager.ts
  src/components/Toolbar/Category/file.ts
  src/locales/en.json
Labels: feature

#755 feat: terminal
  index.html
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/fs_extra.rs
  src-tauri/src/main.rs
  src-tauri/src/terminal.rs
  src/App.ts
  src/App.vue
  src/components/BottomPanel/BottomPanel.css
  src/components/BottomPanel/BottomPanel.tsx
  src/components/BottomPanel/BottomPanel.vue
  src/components/BottomPanel/PanelContent.tsx
  src/components/BottomPanel/TabBar.tsx
  src/components/BottomPanel/Terminal/Input.tsx
  src/components/BottomPanel/Terminal/Output.tsx
  src/components/BottomPanel/Terminal/Terminal.css
  src/components/BottomPanel/Terminal/Terminal.ts
  src/components/CommandBar/CommandBar.vue
  src/components/Common/WindowResize.ts
  src/components/Compiler/LogPanel/Panel.tsx
  src/components/Compiler/Sidebar/create.ts
  src/components/Compiler/Window/Window.ts
  src/components/Compiler/Worker/Console.ts
  src/components/Composables/Sidebar/useSidebarState.ts
  src/components/Sidebar/Content/Main.vue
  src/components/Sidebar/Sidebar.vue
  src/components/Solid/Directives/Model/Model.ts
  src/components/Solid/Directives/Ripple/Ripple.css
  src/components/Solid/Directives/Ripple/Ripple.ts
  src/components/Solid/Icon/IconText.tsx
  src/components/Solid/Icon/SolidIcon.tsx
  src/components/Solid/Inputs/IconButton/IconButton.css
  src/components/Solid/Inputs/IconButton/IconButton.tsx
  src/components/Solid/Inputs/TextField/TextField.css
  src/components/Solid/Inputs/TextField/TextField.tsx
  src/components/Solid/SolidSpacer.tsx
  src/components/Solid/toSignal.ts
  src/components/Solid/toVue.ts
  src/components/TabSystem/TabBar.vue
  src/components/TabSystem/TabSystem.vue
  src/components/TabSystem/WelcomeScreen.vue
  src/components/UIElements/DirectoryViewer/ContextMenu/Actions/OpenWith/Snowstorm.ts
  src/components/UIElements/ProjectDisplay.vue
  src/components/Windows/Settings/SettingsState.ts
  src/locales/en.json
Labels: feature

#758 feat: dynamic type loading
  package-lock.json
  package.json
  public/packages.zip
  src/components/Data/TypeLoader.ts
  src/utils/app/dataPackage.ts
Labels: feature, data

#774 fix: open url
  src/App.ts
  src/components/Extensions/Scripts/Modules/utils.ts
  src/components/Toolbar/Category/help.ts
  src/components/Windows/Socials/Main.vue
Labels: feature

#777 feat: download native app button
  src/components/TabSystem/WelcomeScreen.vue
  src/locales/en.json
Labels: feature

#773 upd: new setup flow
  src/components/PackExplorer/HomeView/SetupHint.vue
  src/components/PackExplorer/HomeView/SetupView.vue
  src/components/UIElements/Sheet.vue
  src/components/Windows/InformedChoice/InformedChoice.vue
  src/locales/en.json
Labels: feature

#779 fix: remote alert padding
  src/components/TabSystem/WelcomeScreen.vue
  src/components/WelcomeAlert/Alert.vue
Labels: bug

#781 upd: tauri to v1.2.2
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
Labels: feature

#782 upd: auto open devtools
  src-tauri/src/main.rs
Labels: feature

#786 fix: various conditions for tauri app
  src/components/Projects/Import/fromBrproject.ts
  src/components/Projects/Import/fromMcaddon.ts
  src/components/Projects/Import/fromMcpack.ts
  src/components/Toolbar/Category/file.ts
  src/components/Toolbar/Category/project.ts
  src/components/Windows/Settings/setupSettings.ts
Labels: bug

#776 upd: vite 4 upgrade
  package-lock.json
  package.json
Labels: feature

#791 feat: configure bridge folder
  src/components/BottomPanel/Terminal/Terminal.ts
  src/components/FileSystem/saveOrDownload.ts
  src/components/UIElements/DirectoryViewer/ContextMenu/Actions/RevealInFileExplorer.ts
  src/components/Windows/Settings/SettingsWindow.ts
  src/components/Windows/Settings/setupSettings.ts
  src/locales/en.json
  src/utils/getBridgeFolderPath.ts
  src/utils/getStorageDirectory.ts
Labels: feature

#790 feat: add API to open directory picker
  src/components/Extensions/Scripts/Modules/import.ts
Labels: feature

#800 fix: file dropping
  src-tauri/tauri.conf.json
  src-tauri/tauri.windows.conf.json
Labels: bug

#802 fix: windows file drop
  src/components/FileSystem/Polyfill.ts
Labels: bug

#803 upd(Dash): faster file reads
  src-tauri/src/fs_extra.rs
  src-tauri/src/main.rs
  src/components/Compiler/Worker/TauriFs.ts
Labels: feature

#807 upd(Tauri): optimize getBridgeFolderPath
  src/utils/getBridgeFolderPath.ts
Labels: feature

#814 fix: error upon opening image files
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/fs_extra.rs
  src-tauri/src/main.rs
  src/components/FileSystem/Virtual/File.ts
  src/components/FileSystem/Virtual/Stores/BaseStore.ts
  src/components/FileSystem/Virtual/Stores/TauriFs.ts
  src/utils/loadAsDataUrl.ts
Labels: bug

#817 fix: virtual files
  src/components/BedrockWorlds/BlockLibrary/BlockLibrary.ts
  src/components/BedrockWorlds/BlockLibrary/loadImage.ts
  src/components/Compiler/Worker/FileSystem.ts
  src/components/Compiler/Worker/Plugins/CustomComponent/ComponentSchemas.ts
  src/components/Editors/HTMLPreview/HTMLPreview.ts
  src/components/Extensions/Scripts/JsRuntime.ts
  src/components/FileSystem/FileSystem.ts
  src/components/FileSystem/FileWatcher.ts
  src/components/FileSystem/Virtual/File.ts
  src/components/FileSystem/Virtual/Stores/BaseStore.ts
  src/components/FileSystem/Virtual/Stores/TauriFs.ts
  src/components/ImportFile/BasicFile.ts
  src/components/PackIndexer/Worker/LightningCache/LightningCache.ts
  src/components/Projects/CreateProject/Files/PackIcon.ts
  src/components/Projects/Project/FileChangeRegistry.ts
  src/components/TabSystem/FileTab.ts
  src/utils/file/moveHandle.ts
  src/utils/file/renameHandle.ts
  src/utils/loadAsDataUrl.ts
Labels: bug

#818 feat: better update flow
  src/components/App/Tauri/TauriUpdater.ts
  src/components/Sidebar/Sidebar.vue
  src/components/TaskManager/Task.ts
  src/locales/en.json
Labels: feature

#819 feat: about window
  package-lock.json
  package.json
  postcss.config.js
  src/App.ts
  src/App.vue
  src/components/BottomPanel/BottomPanel.tsx
  src/components/BottomPanel/Terminal/Input.tsx
  src/components/Extensions/Themes/ThemeManager.ts
  src/components/Projects/ProjectChooser/ProjectChooser.vue
  src/components/Sidebar/Sidebar.vue
  src/components/Solid/Directives/Ripple/Ripple.css
  src/components/Solid/Directives/Ripple/Ripple.ts
  src/components/Solid/Inputs/Button/SolidButton.tsx
  src/components/Solid/Inputs/IconButton/IconButton.css
  src/components/Solid/Inputs/IconButton/IconButton.tsx
  src/components/Solid/Inputs/TextField/TextField.css
  src/components/Solid/Inputs/TextField/TextField.tsx
  src/components/Solid/Logo.tsx
  src/components/Solid/SolidRef.ts
  src/components/Solid/Window/Manager.tsx
  src/components/Solid/Window/Window.tsx
  src/components/Solid/toSignal.ts
  src/components/Toolbar/Category/help.ts
  src/components/UIElements/ProjectDisplay.vue
  src/components/Windows/About/AboutWindow.tsx
  src/locales/en.json
  src/main.css
  src/main.ts
  tailwind.config.js
Labels: feature

#820 feat: better discord rpc
  src-tauri/src/discord.rs
  src-tauri/src/main.rs
  src/App.ts
  src/components/Editors/Text/TextTab.ts
  src/components/Editors/TreeEditor/Tab.ts
  src/components/Locales/Manager.ts
  src/components/TabSystem/FileTab.ts
  src/utils/setRichPresence.ts
Labels: feature

#822 fix: mobile context menu
  src/components/ContextMenu/ContextMenu.vue
  src/components/ContextMenu/List.vue
Labels: bug

#823 feat: new error window
  src/components/BottomPanel/Terminal/Input.tsx
  src/components/Notifications/Errors.ts
  src/components/Solid/Inputs/Button/SolidButton.tsx
  src/components/Solid/Inputs/IconButton/IconButton.tsx
  src/components/Solid/Window/Manager.tsx
  src/components/Solid/Window/Window.tsx
  src/components/Windows/Error/ErrorWindow.tsx
  src/locales/en.json
Labels: feature

#828 fix: mobile users native app suggestion (#827)
  src/components/PackExplorer/HomeView/SetupView.vue
Labels: bug
